# remap prefix to Control + a
set -g prefix C-a
# bind 'C-a C-a' to type 'C-a'
bind C-a send-prefix
unbind C-b

set -g default-shell /bin/fish

# Move bar to top
set-option -g status-position top

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# vim-like pane switching
bind k select-pane -U 
bind j select-pane -D 
bind h select-pane -L 
bind l select-pane -R 


setw -g mode-keys vi
